### ISSUE TITLE
Driver Error

### ISSUE THREAD

**Issue by afcsoft** [libvmi/libvmi#1064]
I cannot get LibVMI working.
```
$ sudo vmi-process-list -n win10
Failed to init LibVMI library.
```
From Python:

```
>>> Libvmi("win10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/libvmi-3.6.2-py3.11-linux-x86_64.egg/libvmi/libvmi.py", line 355, in __init__
    check(status, error_msg)
  File "/usr/local/lib/python3.11/dist-packages/libvmi-3.6.2-py3.11-linux-x86_64.egg/libvmi/libvmi.py", line 262, in check
    raise LibvmiError(error)
libvmi.libvmi.LibvmiError: DRIVER
```

Environment: Ubuntu 23.04
VM: QEMU/KVM

**Comment by KarlKeu00** [comment]
I have the same problem.
