### ISSUE TITLE
I can't install rekall correctly

### ISSUE THREAD

**Issue by Kegem0** [libvmi/libvmi#1096]
ubuntu 16.04 
python 3.7.1
xen 4.7.0
vm: windows7_32
libvmi: 0.14.0

I tried to install rekall using readme in tools/windows-offset-finder. At first ubuntu16.04 only had the 3.5.4 python version by default, which caused a number of problems. After I compiled and installed python3.7.1 myself, most of it worked fine, but I encountered this error at the end

```
virtualenv -p python3 venv
source venv/bin/activate
(venv) pip install --upgrade setuptools pip wheel
(venv) git clone https://github.com/google/rekall.git
(venv) pip install --editable rekall/rekall-lib
(venv) pip install --editable rekall/rekall-core
(venv) pip install --editable rekall/rekall-agent
(venv) pip install --editable rekall   （*****error has occurred in this instruction）
```

Installing collected packages: rekall
  Running setup.py develop for rekall
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [172 lines of output]
        running develop
        running develop
        running egg_info
        writing rekall_core.egg-info/PKG-INFO
        writing dependency_links to rekall_core.egg-info/dependency_links.txt
        writing entry points to rekall_core.egg-info/entry_points.txt
        writing requirements to rekall_core.egg-info/requires.txt
        writing top-level names to rekall_core.egg-info/top_level.txt
        reading manifest file 'rekall_core.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        /home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        warning: no previously-included files matching '*' found under directory '.git'
        warning: no previously-included files matching '*' found under directory 'build'
        warning: no previously-included files matching '*.pyc' found under directory 'rekall'
        warning: no previously-included files matching '*.a' found under directory 'tools'
        warning: no previously-included files matching '*.la' found under directory 'tools'
        warning: no previously-included files matching '*.lo' found under directory 'tools'
        warning: no previously-included files matching '*.o' found under directory 'tools'
        warning: no previously-included files found matching '.gitignore'
        warning: no previously-included files found matching '*.pyc'
        writing manifest file 'rekall_core.egg-info/SOURCES.txt'
        running build_ext
        Creating /home/yn/renv/lib/python3.7/site-packages/rekall-core.egg-link (link to .)
        rekall-core 1.7.3.dev67 is already the active version in easy-install.pth
        Installing rekal script to /home/yn/renv/bin
        Installing rekall script to /home/yn/renv/bin
        Installing rekal.py script to /home/yn/renv/bin
        
        Installed /home/yn/rekall/rekall-core
        Processing dependencies for rekall-core==1.7.3.dev67
        Traceback (most recent call last):
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3109, in _dep_map
            return self.__dep_map
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2902, in __getattr__
            raise AttributeError(attr)
        AttributeError: _DistInfoDistribution__dep_map
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
            parsed = _parse_requirement(requirement_string)
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
            return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
            url, specifier, marker = _parse_requirement_details(tokenizer)
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
            specifier = _parse_specifier(tokenizer)
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 217, in _parse_specifier
            tokenizer.consume("WS")
          File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
            next(self.gen)
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 189, in enclosing_tokens
            span_start=open_position,
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 168, in raise_syntax_error
            span=span,
        pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
            pytz (>=2011k)
                 ~~~~~~~^
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "setup.py", line 181, in <module>
            "pypiwin32",
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py", line 126, in install_for_development
            self.process_distribution(None, self.dist, not self.no_deps)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
            [requirement], self.local_index, self.easy_install
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
            new_requirements = dist.requires(req.extras)[::-1]
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2822, in requires
            dm = self._dep_map
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3111, in _dep_map
            self.__dep_map = self._compute_dependencies()
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3121, in _compute_dependencies
            reqs.extend(parse_requirements(req))
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3174, in __init__
            super(Requirement, self).__init__(requirement_string)
          File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
            raise InvalidRequirement(str(e)) from e
        pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
            pytz (>=2011k)
                 ~~~~~~~^
        Installing rekall-core from local directory.
        /home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/yn/rekall/setup.py", line 132, in <module>
            data_files=find_data_files("tools"),
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/yn/rekall/setup.py", line 76, in run
            cwd="rekall-core")
          File "/usr/local/lib/python3.7/subprocess.py", line 341, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/home/yn/renv/bin/python', 'setup.py', 'develop']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [172 lines of output]
    running develop
    running develop
    running egg_info
    writing rekall_core.egg-info/PKG-INFO
    writing dependency_links to rekall_core.egg-info/dependency_links.txt
    writing entry points to rekall_core.egg-info/entry_points.txt
    writing requirements to rekall_core.egg-info/requires.txt
    writing top-level names to rekall_core.egg-info/top_level.txt
    reading manifest file 'rekall_core.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    warning: no previously-included files matching '*' found under directory '.git'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*.pyc' found under directory 'rekall'
    warning: no previously-included files matching '*.a' found under directory 'tools'
    warning: no previously-included files matching '*.la' found under directory 'tools'
    warning: no previously-included files matching '*.lo' found under directory 'tools'
    warning: no previously-included files matching '*.o' found under directory 'tools'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '*.pyc'
    writing manifest file 'rekall_core.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/yn/renv/lib/python3.7/site-packages/rekall-core.egg-link (link to .)
    rekall-core 1.7.3.dev67 is already the active version in easy-install.pth
    Installing rekal script to /home/yn/renv/bin
    Installing rekall script to /home/yn/renv/bin
    Installing rekal.py script to /home/yn/renv/bin
    
    Installed /home/yn/rekall/rekall-core
    Processing dependencies for rekall-core==1.7.3.dev67
    Traceback (most recent call last):
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3109, in _dep_map
        return self.__dep_map
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2902, in __getattr__
        raise AttributeError(attr)
    AttributeError: _DistInfoDistribution__dep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
        parsed = _parse_requirement(requirement_string)
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
        return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
        url, specifier, marker = _parse_requirement_details(tokenizer)
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
        specifier = _parse_specifier(tokenizer)
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 217, in _parse_specifier
        tokenizer.consume("WS")
      File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
        next(self.gen)
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 189, in enclosing_tokens
        span_start=open_position,
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 168, in raise_syntax_error
        span=span,
    pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
        pytz (>=2011k)
             ~~~~~~~^
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "setup.py", line 181, in <module>
        "pypiwin32",
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py", line 126, in install_for_development
        self.process_distribution(None, self.dist, not self.no_deps)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
        [requirement], self.local_index, self.easy_install
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
        new_requirements = dist.requires(req.extras)[::-1]
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2822, in requires
        dm = self._dep_map
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3111, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3121, in _compute_dependencies
        reqs.extend(parse_requirements(req))
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3174, in __init__
        super(Requirement, self).__init__(requirement_string)
      File "/home/yn/renv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
        raise InvalidRequirement(str(e)) from e
    pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
        pytz (>=2011k)
             ~~~~~~~^
    Installing rekall-core from local directory.
    /home/yn/renv/lib/python3.7/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/yn/rekall/setup.py", line 132, in <module>
        data_files=find_data_files("tools"),
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/yn/renv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yn/rekall/setup.py", line 76, in run
        cwd="rekall-core")
      File "/usr/local/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/yn/renv/bin/python', 'setup.py', 'develop']' returned non-zero exit status 1.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tklengyel** [comment]
Rekall is pretty much dead, just use volatility3

**Comment by tklengyel** [comment]
Also, the recommended way is not to use the windows offsets anymore in libvmi.conf but to generate an IST JSON Profile for your target: https://github.com/libvmi/libvmi?tab=readme-ov-file#volatility3-intermediate-symbol-table-ist-format
