### ISSUE TITLE
pyvmi initilized with a dictionary corrupts the Python interpreter

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#446]
Hi !
I was trying to use `pyvmi` initialized with a dictionary, which works, but almost every function call afterwards crashes with always the same error message, altought the displayed error seems impossible.

This is my test code
~~~Python
#!/usr/bin/env python2

import pyvmi
import time

config = {
        "name": "Windows_7_x64",
        "ostype": "Windows",
        "inittype": "complete",
        "win_tasks": 0x188,
        "win_pdbase": 0x28,
        "win_pid": 0x180,
        "win_pname": 0x2e0
        }

vm = pyvmi.init(config)
time.sleep(10)
~~~

The line `vm = pyvmi.init(config)` executes correctly, but then, when i arrive at `time.sleep(10)`
~~~
Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    time.sleep(10)
TypeError: function takes exactly 2 arguments (1 given)
~~~
Which does not make any sense.

Trying to make another function call after `vm = pyvmi.init(config)`, like the following:
~~~Python
vm = pyvmi.init(config)
logging.debug('pyvmi initialized {}'.format("OK"))
~~~
Results in the exact same error :
~~~
Traceback (most recent call last):
  File "./test.py", line 19, in <module>
    logging.debug('pyvmi initialized {}'.format("OK"))
TypeError: function takes exactly 2 arguments (1 given)
~~~

Can you reproduce this issue ?
Thanks !

**Comment by Wenzel** [comment]
Closing this issue as #532 has been merged.
