### ISSUE TITLE
How to use windows-offset-finder if I can't locate the memory

### ISSUE THREAD

**Issue by allanng78** [libvmi/libvmi#559]
I need to create libvmi.conf for my guest windows. I am not able to identify the memory dump to run windows-offset-finder. I also try to use the memory-dump.o in libvmi and receive an error of the file is not executable. I need help on this. 

First question is how can I locate the memory. If need to use memory-dump.o. How can I solve the non-executable error. 

Please help. Thanks.

**Comment by Wenzel** [comment]
hi @allanng78 ,

can i suggest you to use Rekall to extract the offsets ?
I wrote an article on my blog here : https://wenzel.github.io/2017/11/23/dynamic_configuration_libvmi.html

I hope it helps !

**Comment by buekera** [comment]
Hi @Wenzel 
I'm trying to get the _rekall_offset_finder.py_ to work but always get this error:

```
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "./rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/badseed/Repos/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/guess_profile.py", line 738, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win10_gaqm.
```

To me it seems like libvmi is not even initialized but I really don't know how to check properly as I'm new to all this.
While compiling libvmi there was no error and I also checked all dependencies.
I'm on arch linux.

Thanks for your help.

**Comment by Wenzel** [comment]
@buekera do youo mind jumping on Gitter ?
https://gitter.im/libvmi

**Comment by Wenzel** [comment]
@buekera  could you recompile libvmi with debug messages to see if libvmi is being initialized, and then Rekall fails ?

**Comment by buekera** [comment]
The Problem was libvmi not initializing because the path to the lib was not loaded into my system.

Thanks @Wenzel for helping me with this.
