### ISSUE TITLE
 ./downloadPDB.py ：always got an Windows_7.pdb size of 0...

### ISSUE THREAD

**Issue by gx0417** [libvmi/libvmi#578]
ntkrnlmp.pd_: Success
Traceback (most recent call last):
  File "./dumpPDB.py", line 194, in <module>
    main()
  File "./dumpPDB.py", line 186, in main
    dump_types(infile, opts.outfile)
  File "./dumpPDB.py", line 159, in dump_types
    pdb = pdbparse.parse(pdbFile) #call the parse function in __init__ of the pdbparse library
  File "/usr/local/lib/python2.7/dist-packages/pdbparse/__init__.py", line 490, in parse
    raise ValueError("Unsupported file type")
ValueError: Unsupported file type

gx@gx:~/Desktop/libvmi-master/tools/windows-offset-finder$ ll
total 2097228
drwxrwxr-x  2 gx gx       4096 2月  28 15:51 ./
drwxrwxr-x 10 gx gx       4096 2月  15 00:00 ../
-rwxr-xr-x  1 gx gx       2546 2月  15 00:00 createConfig.py*
-rwxr-xr-x  1 gx gx       4653 2月  28 15:51 downloadPDB.py*
-rwxr-xr-x  1 gx gx       6344 2月  15 00:00 dumpPDB.py*
-rwxrwxr-x  1 gx gx      19520 2月  28 12:24 getGUID*
-rwxr-xr-x  1 gx gx      14934 2月  15 00:00 getGUID.cpp*
-rw-rw-r--  1 gx gx       4482 2月  15 00:00 README
-rw-rw-r--  1 gx gx 2147483648 2月  28 12:22 win7-1.dd
-rw-r--r--  1 gx gx          0 2月  28 15:51 Windows_7.pdb

**Comment by Wenzel** [comment]
Hello,

I just provided a new script to extract the offsets using `Rekall`:
https://github.com/libvmi/libvmi/blob/master/tools/windows-offset-finder/rekall_offset_finder.py

I think it will be easier to use than the set of exsiting scripts to extract the offsets from the PDBs.
Do you want to give it a try maybe ?
