### ISSUE TITLE
Possible cause of xen_get_memory_pfn failure ?

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#579]
Hi,

i'm building the `VMIAddressSpace` for `Rekall`, and now i'm having an issue with Libvmi and Xen:

I am trying to read the physical memory, it works fine, until a certain point:
~~~
--xen_get_memory_pfn success on pfn=0x9c
--MEMORY cache set 0x9d000
--xen_get_memory_pfn success on pfn=0x9d
--MEMORY cache set 0x9e000
--xen_get_memory_pfn success on pfn=0x9e
--MEMORY cache set 0x9f000
--xen_get_memory_pfn success on pfn=0x9f
--MEMORY cache set 0xa0000
--xen_get_memory_pfn failed on pfn=0xa0
Traceback (most recent call last):
  File "./r2vmi.py", line 54, in <module>
    ex = main(docopt(__doc__, version='0.1'))
  File "./r2vmi.py", line 44, in main
    output = session.plugins.pslist()
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/usr/local/lib/python3.5/dist-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/guess_profile.py", line 761, in calculate
    profile_obj = self.ScanProfiles()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/guess_profile.py", line 629, in ScanProfiles
    return self._ScanProfiles()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/guess_profile.py", line 682, in _ScanProfiles
    for offset, hit in scanner.scan(maxlen=autodetect_scan_length):
  File "/usr/local/lib/python3.5/dist-packages/rekall/scan.py", line 467, in scan
    self.session, self.address_space, offset, end):
  File "/usr/local/lib/python3.5/dist-packages/rekall/scan.py", line 328, in __next__
    phys_chunk_offset, chunk_size))
  File "/home/tarrma/fsecure/radare2-extras/vmi/vmiaddressspace.py", line 33, in read
    buffer, bytes_read = self.vmi.read_pa(addr, size)
  File "/usr/local/lib/python3.5/dist-packages/PyVMI-2.0-py3.5-linux-x86_64.egg/libvmi/libvmi.py", line 355, in read_pa
    check(status)
  File "/usr/local/lib/python3.5/dist-packages/PyVMI-2.0-py3.5-linux-x86_64.egg/libvmi/libvmi.py", line 83, in check
    raise LibvmiError(error)
libvmi.libvmi.LibvmiError: VMI_FAILURE
~~~

What could be the cause of `xen_get_memory_pfn` to **fail** ? :thinking: 

If you already had this behavior before, or any ideas, that would help !

Thanks.

**Comment by Wenzel** [comment]
I tried the address space with KVM and it works fine.
So the problem must come from Xen ?

**Comment by tklengyel** [comment]
Well, the most likely answer is that those PFNs are not mappable under Xen.

**Comment by Wenzel** [comment]
@tklengyel can i ask you to inspect a domain with Rekall under Xen to see if you have the same issue ?
I was able to list the processes under a Xen domain a month ago, but i worked on KVM a bit, and surprisingly, something has changed in my environment because i can't get this rekall thing working with Xen anymore.

I would like to understand if it comes from my laptop, or if i made a mistake in the VMIAddressSpace.

~~~
git clone https://github.com/google/rekall
virtualenv -p python3 venv
source venv/bin/activate
pip install --upgrade setuptools pip wheel
pip install --editable rekall/rekall-lib
pip install --editable rekall/rekall-core
pip install --editable rekall/rekall-agent
pip install --editable rekall
~~~

Then install the libvmi cffi bindings from the PR

~~~
source venv/bin/activate
cd libvmi/tools/pyvmi
./setup.py build
./setup.py install
~~~

And you should be able to inspect a windows domain:
~~~
source venv/bin/activate
rekall -f vmi://<domain> pslist
~~~

**Comment by Wenzel** [comment]
I think this might be related to how we set the range of addresses in the VMIAddressSpace.

I copy pasted the code from `pyvmiaddressspace`:
https://github.com/libvmi/libvmi/blob/master/tools/pyvmi/pyvmiaddressspace.py#L93

~~~Python
    def is_valid_address(self, addr):
        if addr == None:
            return False
    return 4096 < addr < self.vmi.get_memsize() - 1

    def get_available_addresses(self):
        yield (4096, self.vmi.get_memsize() - 4096)
    return
~~~

Why the address space starts at `4096` and not 0 ?
Is Xen mapping something not related to the guest memory here ?

**Comment by Wenzel** [comment]
@tklengyel  I built a Vagrant environement with Xen Libvmi and Rekall and i get the same error.
We should look at the `VmiAddressSpace` mappings.

**Comment by Wenzel** [comment]
I just tested with my fresh Volatility `VMIAddressSpace`, and i can list the Windows processes under `Xen`.

I would say the problem is related to this `get_mappings` implementation.

And I tried a fix by using a start address at `4096`
~~~Python
    def get_mappings(self, start=0, end=2 ** 64):
        yield addrspace.Run(start=4096, end=self.vmi.get_memsize(), file_offset=0, **address_space=self)**
~~~

And it doesn't work :/

**Comment by tklengyel** [comment]
I did notice that `end` was previously set to `self.vmi.get_memsize() - 4096`, doubt that's the key problem though but then again I don't really know what might be the root cause either.. I'll try to take a look but it might be a while before I have chance, my schedule is a bit packed at the moment.

**Comment by Wenzel** [comment]
A little update:
I had some errors on KVM, and following what @scudette said, my mappings were inconsistent.
meaning that the `get_mappings` method started at address `0`,
but at the same time i kept the old implementation of `is_valid_address` where you were starting at address `4096`

I forced everything to start at 0:
https://github.com/google/rekall/pull/384/commits/271ad46ad6fb8cb00cbb341174dca9f049801a13

And also I implemented a check in the `read` method, if `vmi_read_pa` failed, we should still return a `buffer`containing zeroes:
https://github.com/google/rekall/pull/384/commits/d1520bcef72aa5a1cfce3190813c9a912ea3b525

Why ?
> A read() method raises RuntimeError() which is strange since read() should always succeed (it may return null padding). The read() method is always expected to return the number of bytes requested. This is analogous to real machine memory - you can do a memcpy from a physical memory range which does not exist and you would just get zeros (or a BSOD but we assume this is handled :-).

These 2 fixes makes both Xen and KVM work now :)
~~~
sudo ./venv-rekall/bin/rekall -f vmi://xen/xenwin7 pslist
LibVMI Version 0.11.0
LibVMI Driver Mode 0
--completed driver init.
--got id from name (xenwin7 --> 2)
**set image_type = xenwin7
**set allocated_ram_size = 7d04b000, max_physical_address = 0xff000000
  _EPROCESS            name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
-------------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
0xfa8001787890 System                   4      0           76          444          - False  2018-03-16 21:53:40Z     -                       
0xfa80027efb30 smss.exe               248      4            2           29          - False  2018-03-16 21:53:40Z     -                       
0xfa8002f50b30 spoolsv.exe            272    460           12          264          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002cf5060 csrss.exe              316    308            8          281          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002eff740 svchost.exe            328    460           15          392          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002d35060 wininit.exe            364    308            3           74          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002d29060 csrss.exe              376    356            7          132          1 False  2018-03-16 21:53:42Z     -                       
0xfa8002d62060 winlogon.exe           416    356            3          108          1 False  2018-03-16 21:53:42Z     -                       
0xfa8002cfd2c0 services.exe           460    364            6          179          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002cbcb30 lsass.exe              468    364            6          505          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002cbb310 lsm.exe                476    364            9          135          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002e0ab30 svchost.exe            580    460           10          335          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002cae3c0 svchost.exe            644    460            6          205          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002e3f890 svchost.exe            696    460           18          409          0 False  2018-03-16 21:53:42Z     -                       
0xfa8002eab890 svchost.exe            820    460           16          396          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002eb5740 svchost.exe            852    460           28          868          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002a4b320 svchost.exe            992    460           10          241          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002f9bb30 svchost.exe           1040    460           17          306          0 False  2018-03-16 21:53:43Z     -                       
0xfa8002ff3b30 taskhost.exe          1144    460            7          139          1 False  2018-03-16 21:53:44Z     -                       
0xfa8003013060 dwm.exe               1228    820            3           67          1 False  2018-03-16 21:53:44Z     -                       
0xfa80030254a0 svchost.exe           1236    460            8          154          0 False  2018-03-16 21:53:44Z     -                       
0xfa800302a5a0 explorer.exe          1260   1208           19          595          1 False  2018-03-16 21:53:44Z     -                       
0xfa8003089b30 sppsvc.exe            1388    460            6          145          0 False  2018-03-16 21:53:44Z     -                       
0xfa80030b0340 wlms.exe              1456    460            4           43          0 False  2018-03-16 21:53:44Z     -                       
0xfa8002e6a440 svchost.exe           1924    460            5           89          0 False  2018-03-16 21:53:46Z     -                       
0xfa800319b630 WmiPrvSE.exe          1980    580            7          119          0 False  2018-03-16 21:57:44Z     -                       
0xfa8003083570 svchost.exe           2004    460           12          337          0 False  2018-03-16 21:55:45Z     -  
~~~

**Comment by tklengyel** [comment]
Sweet! Great job :)
