### ISSUE TITLE
Generating Config for windows 7 using Rekall

### ISSUE THREAD

**Issue by mbhatt1** [libvmi/libvmi#628]
Hi there, 

I am attempting to generate config of a win7 vm on Xen using the rekall_offset_finder.py. I keep getting the following error:
  File "rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, 'vmi:///xen/win7')
  File "rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 912, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/usr/local/lib/python3.6/dist-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///xen/win7.

Can someone please help me with this?

Do I have to change something in my xend-config file under /etc/xen ? 
I currently have the xen-unix-server setting turned on. 

The older way of using the dumpPDB.py and then parsing the pdb doesn't work either. It tells me:

construct.core.StringError: encoding 'names' not found among {'utf_8': 1, 'utf32': 4, 'utf_32_le': 4, 'utf8': 1, 'utf_32_be': 4, 'u16': 2, 'utf_32': 4, 'utf_16_be': 2, 'u32': 4, 'utf16': 2, 'ascii': 1, 'utf_16': 2, 'utf_16_le': 2, 'u8': 1}

when I do ./getUID <dump> | ./downloadPDB.py | ./dumpPDB.py -p debugSymbols.txt

Manish

**Comment by Wenzel** [comment]
Hi,

1. please use the Github flavored markdown to format your issues, especially the code, otherwise it's quite difficult to read.
2. you have a small mistake when you call the script:
from this line: `config = extract_offsets(domain, 'vmi:///xen/win7')`, i can see that you called it with:
~~~
$ ./rekall_offset_finder.py vmi:///xen/win7
~~~

use 2 slashes if you want to specify the hypervisor, and 3 otherwise.
so either:
- `vmi://xen/win7`
- or `vmi:///win7`

For more information about this behavior, i'm simply parsing the url with `urlparse`.
A URL has the following convention:
~~~
scheme://netloc/path;parameters?query#fragment
~~~

the netloc here is the hypervisor :)

**Comment by mbhatt1** [comment]
Hello, 

Sorry about not using Markdown.
```
  File "rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 912, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/usr/local/lib/python3.6/dist-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7
```
I get the same error again. I hardcoded it earlier to see if that will do anything but I used the original script right now. 

Cheers, 
Manish

**Comment by Wenzel** [comment]
1. can you post the command line ?
2. are you in a virtualenv
3. what version of rekall are you using ?
4. do you have the python bindings installed ?

**Comment by mbhatt1** [comment]
Hi, 
1. I did 
```
 sudo python3 rekall_offset_finder.py vmi:///win7
```
2. I'm not in a virtualenv right now. I just did it inside a venv and still got the same error. 

```
sudo venv/bin/python rekall_offset_finder.py vmi://xen/win7

  File "rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 912, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/the-sage/libvmi/tools/windows-offset-finder/venv/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7
```
3. Version is 1.7.2.rc1
4. Yes. 
![image](https://user-images.githubusercontent.com/5893997/40589808-f24ba1b6-61b9-11e8-9548-5f23215dc706.png)

**Comment by Wenzel** [comment]
I just tried to install Rekall from git, and i have a different version than yours:
~~~
$ which rekall
~/tmp/venv/bin/rekall
$ rekall --version
This is Rekall Version 1.7.3.dev22 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.3', 'revisionid': b'5132170b32895385872ddb35296dcdf6bc1d2512', 'dirty': False, 'dev': 22, 'pep440': '1.7.3.dev22'}
~~~

A good way to debug would be by using rekall directly:
~~~
$ sudo ./venv/bin/rekall -f vmi:///win7 pslist -v
~~~

And paste the output here.

**Comment by Wenzel** [comment]
My blind guess is that you installed Rekall with `pip install rekall`, but this doesn't install the the latest version available from git.

**Comment by mbhatt1** [comment]
Hi, 

I reinstalled rekall from git using the steps in the README file

```
(venv) <>$ which rekall
/home/the-sage/Desktop/venv/bin/rekall
```

Rekall version
```
(venv) <>$ rekall --version
This is Rekall Version 1.7.3.dev22 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.3', 'revisionid': b'5132170b32895385872ddb35296dcdf6bc1d2512', 'dirty': False, 'dev': 22, 'pep440': '1.7.3.dev22'}

```

Output of the command you asked for
```
<>$ sudo ./venv/bin/rekall -f vmi:///win7 pslist -v
2018-05-27 15:04:59,752:DEBUG:rekall.1:Logging level set to 10
2018-05-27 15:04:59,754:DEBUG:rekall.1:Voting round with base: None
2018-05-27 15:04:59,754:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-05-27 15:04:59,754:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-05-27 15:04:59,755:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-05-27 15:04:59,755:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-05-27 15:04:59,755:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-05-27 15:04:59,755:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-05-27 15:04:59,755:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-05-27 15:04:59,756:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-05-27 15:04:59,756:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-05-27 15:04:59,756:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-05-27 15:04:59,756:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-05-27 15:04:59,756:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-05-27 15:04:59,757:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-05-27 15:04:59,758:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-05-27 15:04:59,758:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-05-27 15:04:59,758:DEBUG:rekall.1:Unable to open AFF4 image Not found: file:vmi%3A///win7
2018-05-27 15:04:59,759:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
2018-05-27 15:04:59,759:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-05-27 15:04:59,759:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Filename does not exist or can not be opened.
2018-05-27 15:04:59,759:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-05-27 15:04:59,759:DEBUG:rekall.1:Failed instantiating FileAddressSpace: [Errno 2] No such file or directory: '/home/the-sage/Desktop/vmi:/win7'
2018-05-27 15:04:59,759:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-05-27 15:04:59,759:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: 
2018-05-27 15:04:59,759:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-05-27 15:04:59,759:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-05-27 15:04:59,760:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-05-27 15:04:59,760:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-05-27 15:04:59,760:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-05-27 15:04:59,760:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
Traceback (most recent call last):
  File "./venv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/the-sage/Desktop/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/the-sage/Desktop/rekall/rekall-core/rekall/plugins/guess_profile.py", line 738, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7.
```
I don't know what the error means. Sorry for my noobness. 

Manish

**Comment by Wenzel** [comment]
Ok, now i can see why the VMIAddressSpace was not instantiated:
~~~
2018-05-27 15:04:59,757:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-05-27 15:04:59,758:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
~~~

You must install the libvmi python bindings :)
https://github.com/libvmi/python

**Comment by Wenzel** [comment]
That's weird, it means that this entry doesn't have the format that i was expected.
https://github.com/libvmi/libvmi/blob/master/tools/windows-offset-finder/rekall_offset_finder.py#L19

This script is not very robust, we could improve it
Could you try to debug it and figure out what's in this entry ?

Thanks

**Comment by mbhatt1** [comment]
I'll see what I can do. :)

**Comment by enjhnsn2** [comment]
@mbhatt1 was it ever discovered what the problem here was? This is the exact issue I currently have

**Comment by mbhatt1** [comment]
use rekall directly as a workaround. 
```
1. Compile the getGUID.cpp file
2. Copy the GUID after you run the file against a memory dump, which you would obtain via the example dump-memory.c program. 
3. use rekall :
          rekall fetchpdb ntkrpamp <GUID>
4. If you want a rekall json profile, do the following:
         rekall parse_pdb ntkrpamp > JSONFILE.json
```

Sorry kinda pushing a deadline here. This is one of the things on my huge list. Let me know if this helped.

**Comment by enjhnsn2** [comment]
@mbhatt1 Ya, that was helpful, thanks

**Comment by mbhatt1** [comment]
Sure thing :)

**Comment by mbhatt1** [comment]
Also try the same thing for windows 10 and let me know how that goes @enjhnsn2 ? If you can.
