### ISSUE TITLE
Driver Error during rekall dynamic profile

### ISSUE THREAD

**Issue by enjhnsn2** [libvmi/libvmi#630]
Hello, I'm having a tad bit of an issue running windows-offset-finder/rekall_offset_finder.py.
The machine runs fine fine with libvirt, so I'm not sure why libvmi is unable to find the driver. I am using qemu/kvm with a windows 10 guest and an ubuntu 18.0.4 host.

Command used: python rekall_offset_finder.py  vmi://kvm/win10

Thank you for your time

```
Traceback (most recent call last):
  File "rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/rekall/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/rekall/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/rekall/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/rekall/rekall/rekall-core/rekall/plugins/guess_profile.py", line 731, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home/rekall/rekall/rekall-core/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home/rekall/rekall/rekall-core/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/rekall/rekall/rekall-lib/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/rekall/rekall/rekall-core/rekall/plugins/addrspaces/vmi.py", line 52, in __init__
    self.vmi = Libvmi(domain, mode=self.mode, partial=True)
  File "/usr/local/lib/python3.6/dist-packages/libvmi-3.0-py3.6-linux-x86_64.egg/libvmi/libvmi.py", line 208, in __init__
    check(status, error_msg)
  File "/usr/local/lib/python3.6/dist-packages/libvmi-3.0-py3.6-linux-x86_64.egg/libvmi/libvmi.py", line 131, in check
    raise LibvmiError(error)
libvmi.libvmi.LibvmiError: DRIVER



```

**Comment by Wenzel** [comment]
Hi,

To know the source of the driver issue, enable all the debug messages in `libvmi/debug.h`.
Then recompile, reinstall the library, and run the script again.

**Comment by Wenzel** [comment]
@enjhnsn2 did you find the root cause of your issue ?

**Comment by enjhnsn2** [comment]
@Wenzel 
This is the additional info produced by debug
```
LibVMI Version 0.13.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (win10 --> 1)
**set image_type = win10
--libvirt version 4000000
--qmp: virsh -c qemu:///system qemu-monitor-command win10 '{"execute": "pmemaccess", "arguments": {"path": "/tmp/vmi3IqStz"}}'
--kvm: using custom patch for fast memory access
--connect() failed to /tmp/vmi3IqStz, No such file or directory
```

When I run the virsh command manually, it returns:
`{"id":"libvirt-50","error":{"class":"GenericError","desc":"Qemu pmemaccess: bind failed"}}`

This appears to be an issue with the qmp commands added by the qemu-kvm patch, as other qmp commands work with virsh I used the qemu 2.12 patch (I am using Qemu 2.12.50) available in the pull requests as consensus seemed to be that it worked fine.
I'll update it I manage to figure out whats happening.

**Comment by Wenzel** [comment]
Why the `bind` syscall fails might be because of apparmor ?
maybe QEMU is not allowed to create files in /tmp.

i advise you to take a look at `dmesg` and see if you can find some `DENIED` messages.
It already happened to me before :)

**Comment by enjhnsn2** [comment]
Yup, it appears to be an AppArmor issue, thanks!

**Comment by smaresca** [comment]
@enjhnsn2 thanks for confirming that was the underlying cause
