### ISSUE TITLE
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7.

### ISSUE THREAD

**Issue by Shockmeister** [libvmi/libvmi#631]
Hi

I'm getting the above error when running the windows-offset-finder.py script. The output is below. I note this is the same as this issue:

https://github.com/libvmi/libvmi/issues/559

However, it was unclear how the problem was resolved

./rekall_offset_finder.py vmi:///win7
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "./rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 912, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/stephen/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7.

Outputs 
./configure 
[configure.txt](https://github.com/libvmi/libvmi/files/2063183/configure.txt)

make
[make.txt](https://github.com/libvmi/libvmi/files/2063185/make.txt)

sudo make install:
[makeinstall.txt](https://github.com/libvmi/libvmi/files/2063188/makeinstall.txt)

Thanks!

**Comment by Wenzel** [comment]
Hi,

Can you post the output of `rekall -f vmi:///win7 pslist -v` ?

**Comment by Shockmeister** [comment]
Hi,

Here's the output: 

2018-06-01 20:10:47,542:DEBUG:rekall.1:Logging level set to 10
2018-06-01 20:10:47,543:DEBUG:rekall.1:Voting round with base: None
2018-06-01 20:10:47,543:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-06-01 20:10:47,544:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-06-01 20:10:47,544:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-06-01 20:10:47,544:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-06-01 20:10:47,544:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-06-01 20:10:47,544:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-06-01 20:10:47,544:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-06-01 20:10:47,544:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-06-01 20:10:47,544:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-06-01 20:10:47,545:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-06-01 20:10:47,545:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-06-01 20:10:47,545:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-06-01 20:10:47,545:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-06-01 20:10:47,545:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-06-01 20:10:47,545:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-06-01 20:10:47,546:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-06-01 20:10:47,546:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-06-01 20:10:47,546:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-06-01 20:10:47,546:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-06-01 20:10:47,546:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-06-01 20:10:47,546:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-06-01 20:10:47,546:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-06-01 20:10:47,546:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-06-01 20:10:47,547:DEBUG:rekall.1:Unable to open AFF4 image Not found: file:vmi%3A///win7
2018-06-01 20:10:47,547:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
2018-06-01 20:10:47,547:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-06-01 20:10:47,547:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Filename does not exist or can not be opened.
2018-06-01 20:10:47,547:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-06-01 20:10:47,547:DEBUG:rekall.1:Failed instantiating FileAddressSpace: [Errno 2] No such file or directory: '/home/stephen/MemoryAnalysis/libvmi/tools/windows-offset-finder/vmi:/win7'
2018-06-01 20:10:47,547:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-06-01 20:10:47,547:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: 
2018-06-01 20:10:47,548:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-06-01 20:10:47,548:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-06-01 20:10:47,548:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-06-01 20:10:47,548:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-06-01 20:10:47,548:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-06-01 20:10:47,548:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
Traceback (most recent call last):
  File "/home/stephen/venv/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/stephen/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/stephen/venv/lib/python3.5/site-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7.

**Comment by Wenzel** [comment]
I can't see any trace of the VMIAddressSpace here.

you installed rekall from pip, and not from the git repository.
Please install from git, as indicated in the README.
And post your `rekall --version`

**Comment by Shockmeister** [comment]
I've reinstalled rekall from source. Still having problems!

Outputs:

rekall --version
This is Rekall Version 1.7.3.dev24 (Hurricane Ridge)
{'pep440': '1.7.3.dev24', 'post': '0', 'dirty': False, 'rc': '1', 'codename': 'Hurricane Ridge', 'version': '1.7.3', 'dev': 24, 'revisionid': b'dd37cea3b1ef19ae38e5cd3f81cf7feeba147d72'}

rekall -f vmi:///win7 pslist -v
2018-06-04 15:11:02,552:DEBUG:rekall.1:Logging level set to 10
2018-06-04 15:11:02,553:DEBUG:rekall.1:Voting round with base: None
2018-06-04 15:11:02,554:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-06-04 15:11:02,554:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-06-04 15:11:02,554:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-06-04 15:11:02,554:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-06-04 15:11:02,554:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-06-04 15:11:02,554:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-06-04 15:11:02,554:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-06-04 15:11:02,555:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-06-04 15:11:02,555:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-06-04 15:11:02,555:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-06-04 15:11:02,555:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-06-04 15:11:02,555:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-06-04 15:11:02,555:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-06-04 15:11:02,556:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-06-04 15:11:02,556:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-06-04 15:11:02,557:DEBUG:rekall.1:Unable to open AFF4 image Not found: file:vmi%3A///win7
2018-06-04 15:11:02,557:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
2018-06-04 15:11:02,557:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-06-04 15:11:02,557:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Filename does not exist or can not be opened.
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Failed instantiating FileAddressSpace: [Errno 2] No such file or directory: '/home/stephen/MemoryAnalysis/libvmi/tools/windows-offset-finder/vmi:/win7'
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-06-04 15:11:02,558:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-06-04 15:11:02,558:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-06-04 15:11:02,559:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
Traceback (most recent call last):
  File "/home/stephen/python/myvenv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/stephen/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/stephen/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/stephen/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/stephen/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/stephen/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/stephen/rekall/rekall-core/rekall/plugins/guess_profile.py", line 738, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win7.

**Comment by Wenzel** [comment]
Look at #632.
Can you inspect the raw memory dump ?

**Comment by Shockmeister** [comment]
Similar output:

rekall -f win7.mem pslist -v
2018-06-04 15:34:17,482:DEBUG:rekall.1:Logging level set to 10
2018-06-04 15:34:17,483:DEBUG:rekall.1:Voting round with base: None
2018-06-04 15:34:17,483:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-06-04 15:34:17,483:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-06-04 15:34:17,483:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-06-04 15:34:17,484:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-06-04 15:34:17,484:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-06-04 15:34:17,484:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-06-04 15:34:17,484:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-06-04 15:34:17,485:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-06-04 15:34:17,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-06-04 15:34:17,485:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-06-04 15:34:17,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-06-04 15:34:17,485:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-06-04 15:34:17,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-06-04 15:34:17,485:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-06-04 15:34:17,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-06-04 15:34:17,485:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-06-04 15:34:17,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-06-04 15:34:17,486:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-06-04 15:34:17,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-06-04 15:34:17,486:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-06-04 15:34:17,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-06-04 15:34:17,486:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-06-04 15:34:17,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-06-04 15:34:17,486:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-06-04 15:34:17,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-06-04 15:34:17,487:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-06-04 15:34:17,487:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-06-04 15:34:17,487:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-06-04 15:34:17,487:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-06-04 15:34:17,487:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Filename does not exist or can not be opened.
2018-06-04 15:34:17,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Failed instantiating FileAddressSpace: [Errno 13] Permission denied: '/home/stephen/win7.mem'
2018-06-04 15:34:17,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-06-04 15:34:17,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-06-04 15:34:17,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-06-04 15:34:17,488:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
Traceback (most recent call last):
  File "/home/stephen/python/myvenv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/stephen/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/stephen/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/stephen/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/stephen/rekall/rekall-core/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/home/stephen/rekall/rekall-core/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/stephen/rekall/rekall-core/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/stephen/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/stephen/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/stephen/rekall/rekall-core/rekall/plugins/guess_profile.py", line 738, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename win7.mem.

**Comment by Wenzel** [comment]
Then it's a problem with rekall.
Please open an issue there and make a référence to this one.

**Comment by Shockmeister** [comment]
Ok thank you!
