### ISSUE TITLE
rekall_offset_finder.py fails to generate profile with Windows 10 Guest

### ISSUE THREAD

**Issue by 0Slugcat0** [libvmi/libvmi#738]
Using KVM/Qemu as hypervisor with the GDB method.

Perhaps this is a duplicate of #634, which shows the exact same errors. Is this a issue with LibVMI or Rekall. 

Any workarounds?

```
./rekall_offset_finder.py win10 vmi:///win10 -d

Webconsole disabled: cannot import name 'webconsole_plugin'
DEBUG:root:{'--debug': True,
 '--help': False,
 '--old': False,
 '--uri': 'qemu:///system',
 '--version': False,
 '<domain>': 'win10',
 '<url>': 'vmi:///win10'}
DEBUG:root:Running plugin (version_modules) with args (()) kwargs ({})
DEBUG:root:Voting round with base: None
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
DEBUG:root:Failed instantiating XenElf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:root:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:root:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:root:Unable to open AFF4 image Not found: file:vmi%3A///win10
DEBUG:root:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:root:Failed instantiating MacPmemAddressSpace: Filename does not exist or can not be opened.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:root:Failed instantiating FileAddressSpace: [Errno 2] No such file or directory: '/home/user/libvmi/tools/windows-offset-finder/vmi:/win10'
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
DEBUG:root:Failed instantiating VTxPagedMemory: 
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
DEBUG:root:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
DEBUG:root:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 177, in <module>
    exit_code = main(args)
  File "./rekall_offset_finder.py", line 170, in main
    config = extract_offsets(domain_name, url)
  File "./rekall_offset_finder.py", line 57, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 986, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/guess_profile.py", line 738, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi:///win10.

```

**Comment by Wenzel** [comment]
hi @0Slugcat0 

you use the `vmi://` url, there the `VMIAddressSpace` is called:

What i see in the logs:
~~~
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
~~~

So you might want to check that.
Otherwise it's not very well tested, especially against Windows 10, so i would recommend just specifying the domain to the script, so that it takes care of dumping the memory and analyzing it.

**Comment by 0Slugcat0** [comment]
It fails with the following log (Thanks for the quick reply btw)

```
./rekall_offset_finder.py -d win10  

Webconsole disabled: cannot import name 'webconsole_plugin'
DEBUG:root:{'--debug': True,
 '--help': False,
 '--old': False,
 '--uri': 'qemu:///system',
 '--version': False,
 '<domain>': 'win10',
 '<url>': None}
INFO:root:Dumping win10 physical memory to /tmp/tmpxy8x191p/tmp28yys05j
DEBUG:root:Running plugin (version_modules) with args (()) kwargs ({})
DEBUG:root:Voting round with base: None
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
DEBUG:root:Failed instantiating XenElf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:root:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:root:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:root:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:root:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /tmp/tmpxy8x191p/tmp28yys05j_info
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:root:Succeeded instantiating FileAddressSpace
DEBUG:root:Voting round with base: FileAddressSpace
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Not kcore
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Succeeded instantiating Elf64CoreDump
DEBUG:root:Voting round with base: Elf64CoreDump
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
DEBUG:root:Failed instantiating XenElf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:root:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:root:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:root:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:root:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:root:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
DEBUG:root:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
DEBUG:root:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
DEBUG:root:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:root:Autodetected physical address space Elf64CoreDump
DEBUG:root:Will detect profile using these Detectors: rsds
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/pe.gz
DEBUG:root:Adding pe to local cache.
INFO:root:Loaded profile pe from Local Cache - (in 0.10606598854064941 sec)
DEBUG:root:Trying method rsds, offset 0
DEBUG:root:Skipped profile nt/GUID/8B11040A5928757B11390AC78F6B69251 from http://profiles.rekall-forensic.com (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/9296E92A72BD4B6D96357332E2E8A5AA1 from http://profiles.rekall-forensic.com (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/2AC01A5FDAC6452D82685CDD622F85971 from http://profiles.rekall-forensic.com (Not in inventory)
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 177, in <module>
    exit_code = main(args)
  File "./rekall_offset_finder.py", line 167, in main
    config = extract_offsets(domain.name(), ram_dump.name)
  File "./rekall_offset_finder.py", line 57, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 986, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
```

**Comment by Wenzel** [comment]
Well, then rekall fails to locate the profile for some Windows 10 builds.
You might want to try installing rekall from github, if it fixes the issue.

Otherwise open an issue on [`google/rekall`](https://github.com/google/rekall)

**Comment by 0Slugcat0** [comment]
Ok, definitively seems something related to rekall and not libVMI.
