### ISSUE TITLE
Issue when trying to use Windows offset finder

### ISSUE THREAD

**Issue by raulney** [libvmi/libvmi#843]
Hello all,

I've been trying to use the rekall_offset_finder.py in order to read the offsets from a Windows Guest VM. I'm getting the following error:

INFO:root:Dumping win7 physical memory to /tmp/tmphcpwao70/tmp3pu3r_b7
INFO:root:Error: NewZipFile() missing 1 required positional argument: 'backing_store_urn'
Traceback (most recent call last):
  File "rekall_offset_finder.py", line 177, in <module>
    exit_code = main(args)
  File "rekall_offset_finder.py", line 167, in main
    config = extract_offsets(domain.name(), ram_dump.name)
  File "rekall_offset_finder.py", line 57, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 912, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/user/.local/lib/python3.5/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugins/addrspaces/aff4.py", line 133, in __init__
    volume_path, stream_path = self._LocateAFF4Volume(path)
  File "/home/user/.local/lib/python3.5/site-packages/rekall/plugins/addrspaces/aff4.py", line 170, in _LocateAFF4Volume
    self.resolver, volume_urn) as volume:
TypeError: NewZipFile() missing 1 required positional argument: 'backing_store_urn'

Rekall seems to be working fine since I'm able to create a Rekall profile from a memory dump and use LibVMI to introspect this Guest using the profile.

I apologize if this is not the correct place to report this.

Thanks in advance.

**Comment by mtarral** [comment]
Hi @raulney ,

I assume you have installed Rekall from git right ?
it looks like a problem in `aff4.py` library, probably because rekall hasn't been maintained in months.
so I wouldn't be surprised that it has been pulling the latest aff4 library that isn't compatible anymore.

You can report this on the Rekall bug tracker.

**Comment by raulney** [comment]
Hi @mtarral,

Thanks for the prompt response.

I've installed Rekall via python pip. Anyways I'm going to report this in Rekall's but tracker.

**Comment by Vladinuto** [comment]
I had the same issue too. It seems that downgrading pyaff4 may be able to help. 

pip install pyaff4==0.26.post6
pip install pyaff4==0.26.post6
